name: vtour
description: A virtual campus tour app for university students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  supabase_flutter: ^2.5.0
  app_links: ^3.5.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.6.0
  location: ^6.0.2
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^3.0.1
  http: ^1.2.0
  audioplayers: ^6.0.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.1.4
  uni_links: ^0.5.1
  shared_preferences: ^2.0.15
  permission_handler: ^11.3.1
  model_viewer_plus: ^1.7.0
  path: ^1.9.1
  panorama: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
    - assets/audio/
    - assets/models/
    - .env